[flake8]
# it is possibble to have prints in scripts
ignore = WPS421
accept-encodings = utf-8
max-complexity = 6
statistics = False
max-line-length = 80
doctests = True
enable-extensions = G
isort-show-traceback = True

[isort]
multi_line_output = 3
include_trailing_comma = true
default_section = FIRSTPARTY
# Should be: 80 - 1
line_length = 79